// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teams.Data;

namespace Teams.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180925144026_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teams.Models.InfoTeams", b =>
                {
                    b.Property<int>("Team_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coach_name");

                    b.Property<int>("Maches_Lost");

                    b.Property<int>("Maches_Played");

                    b.Property<int>("Maches_Won");

                    b.Property<string>("Team_name");

                    b.HasKey("Team_Id");

                    b.ToTable("infoTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
